# Tensor Operations in PyTorch

**Author:** Phabel Antonio López Delgado, BSc.

This notebook explores the fundamental operations that can be performed on tensors. We cover transposition, permutation, addition, scalar multiplication, dot products, matrix multiplication, and element‑wise operations. These operations form the building blocks for neural network computations.

**Key Concepts Covered:**
- Transposition and permutation of tensor dimensions.
- Addition and scalar multiplication.
- Dot product (inner product).
- Matrix‑vector and matrix‑matrix multiplication.
- Higher‑order tensor multiplication.
- Hadamard (element‑wise) product.
- Outer product.

**Key Techniques & Libraries:**
- `torch` – tensor creation and operations.
- `matplotlib` – visualisation (optional).

**Objective:**
To become proficient in tensor operations using PyTorch, which are essential for implementing and training neural networks.

In [1]:
import torch
import numpy as np

print("All imports successful.")

All imports successful.


## 1. Transposition

Transposition reverses the order of tensor indices.

- **Rank 1 (vector):** Transposition has no visible effect (it remains a 1‑D array).
- **Rank 2 (matrix):** Swaps rows and columns: `(A^T)_{i,j} = A_{j,i}`.
- **Rank 3 and above:** Reverses all indices: `(T^T)_{i,j,k} = T_{k,j,i}`.

**Note:** In PyTorch, using `.T` on tensors of dimension other than 2 is deprecated. Use `.mT` for batched matrices or `.permute()` for general cases.

In [2]:
# Rank 1 vector – transposition has no effect
x = torch.tensor([1, 2, 3])
print(f"Vector: {x}")
print(f"Transposed vector: {x.T} (same)")
print("-" * 40)

# Rank 2 matrix – swaps rows and columns
A = torch.tensor([
    [0, 5, 1],
    [3, 0, 2],
    [0, 2, 0],
    [5, 3, 1]
])
print(f"Matrix A:\n{A}")
print(f"Transposed A (A.T):\n{A.T}")
print(f"Shape: {A.shape} -> {A.T.shape}")
print("-" * 40)

# Rank 3 tensor – reverses indices
T = torch.tensor([
    [[1, 2, 3], [4, 5, 6], [1, 2, 3], [1, 0.5, 2]],
    [[7, 8, 9], [10, 11, 12], [20, 1, 0], [0, 0, 1]]
])
print(f"Tensor T shape: {T.shape}")
print(f"Transposed T shape: {T.T.shape}")
print(f"T.T:\n{T.T}")

Vector: tensor([1, 2, 3])
Transposed vector: tensor([1, 2, 3]) (same)
----------------------------------------
Matrix A:
tensor([[0, 5, 1],
        [3, 0, 2],
        [0, 2, 0],
        [5, 3, 1]])
Transposed A (A.T):
tensor([[0, 3, 0, 5],
        [5, 0, 2, 3],
        [1, 2, 0, 1]])
Shape: torch.Size([4, 3]) -> torch.Size([3, 4])
----------------------------------------
Tensor T shape: torch.Size([2, 4, 3])
Transposed T shape: torch.Size([3, 4, 2])
T.T:
tensor([[[ 1.0000,  7.0000],
         [ 4.0000, 10.0000],
         [ 1.0000, 20.0000],
         [ 1.0000,  0.0000]],

        [[ 2.0000,  8.0000],
         [ 5.0000, 11.0000],
         [ 2.0000,  1.0000],
         [ 0.5000,  0.0000]],

        [[ 3.0000,  9.0000],
         [ 6.0000, 12.0000],
         [ 3.0000,  0.0000],
         [ 2.0000,  1.0000]]])


C:\Users\phabe\AppData\Local\Temp\ipykernel_96284\730618415.py:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4317.)
  print(f"Transposed vector: {x.T} (same)")


## 2. Permutation

While transposition reverses all dimensions, `transpose()` allows swapping any two specific dimensions.

In [3]:
print(f"Original T shape: {T.shape}")

# Swap dimension 0 and 1
print(f"T.transpose(0,1) shape: {T.transpose(0, 1).shape}")
print(f"T.transpose(0,1):\n{T.transpose(0, 1)}")

# Swap dimension 1 and 2
print(f"\nT.transpose(1,2) shape: {T.transpose(1, 2).shape}")
print(f"T.transpose(1,2):\n{T.transpose(1, 2)}")

Original T shape: torch.Size([2, 4, 3])
T.transpose(0,1) shape: torch.Size([4, 2, 3])
T.transpose(0,1):
tensor([[[ 1.0000,  2.0000,  3.0000],
         [ 7.0000,  8.0000,  9.0000]],

        [[ 4.0000,  5.0000,  6.0000],
         [10.0000, 11.0000, 12.0000]],

        [[ 1.0000,  2.0000,  3.0000],
         [20.0000,  1.0000,  0.0000]],

        [[ 1.0000,  0.5000,  2.0000],
         [ 0.0000,  0.0000,  1.0000]]])

T.transpose(1,2) shape: torch.Size([2, 3, 4])
T.transpose(1,2):
tensor([[[ 1.0000,  4.0000,  1.0000,  1.0000],
         [ 2.0000,  5.0000,  2.0000,  0.5000],
         [ 3.0000,  6.0000,  3.0000,  2.0000]],

        [[ 7.0000, 10.0000, 20.0000,  0.0000],
         [ 8.0000, 11.0000,  1.0000,  0.0000],
         [ 9.0000, 12.0000,  0.0000,  1.0000]]])


## 3. Tensor Addition

Addition is performed element‑wise. Both tensors must have the same shape.

In [4]:
# Vector addition
x = torch.tensor([1, 2, 1])
y = torch.tensor([1, 2, 2])
print(f"{x} + {y} = {x + y}")
print("-" * 40)

# Matrix addition
A = torch.tensor([[0, 5, 1], [3, 0, 2], [0, 2, 0], [5, 3, 1]])
B = torch.tensor([[10, 0, 2], [9, 4, 1], [8, 1, 0], [1, 0, 0]])
print(f"A + B =\n{A + B}")
print("-" * 40)

# Higher‑rank tensor addition
T1 = torch.rand(2, 3, 4)
T2 = torch.rand(2, 3, 4)
print(f"T1 + T2 =\n{T1 + T2}")

tensor([1, 2, 1]) + tensor([1, 2, 2]) = tensor([2, 4, 3])
----------------------------------------
A + B =
tensor([[10,  5,  3],
        [12,  4,  3],
        [ 8,  3,  0],
        [ 6,  3,  1]])
----------------------------------------
T1 + T2 =
tensor([[[1.1647, 0.8678, 0.1317, 0.9668],
         [1.4383, 0.4876, 0.9676, 0.8869],
         [1.0758, 0.9377, 0.9588, 1.1230]],

        [[0.8517, 1.6388, 1.7686, 0.6205],
         [0.6424, 1.6133, 0.8898, 0.1814],
         [0.6151, 0.7982, 0.8427, 1.7184]]])


## 4. Scalar Multiplication

Multiplying a tensor by a scalar scales every element: `(λT)_{i} = λ * T_{i}`.

In [5]:
scalar = 2.5
print(f"{scalar} * {x} = {scalar * x}")
print(f"{scalar} * A =\n{scalar * A}")
print(f"{scalar} * T =\n{scalar * T}")

2.5 * tensor([1, 2, 1]) = tensor([2.5000, 5.0000, 2.5000])
2.5 * A =
tensor([[ 0.0000, 12.5000,  2.5000],
        [ 7.5000,  0.0000,  5.0000],
        [ 0.0000,  5.0000,  0.0000],
        [12.5000,  7.5000,  2.5000]])
2.5 * T =
tensor([[[ 2.5000,  5.0000,  7.5000],
         [10.0000, 12.5000, 15.0000],
         [ 2.5000,  5.0000,  7.5000],
         [ 2.5000,  1.2500,  5.0000]],

        [[17.5000, 20.0000, 22.5000],
         [25.0000, 27.5000, 30.0000],
         [50.0000,  2.5000,  0.0000],
         [ 0.0000,  0.0000,  2.5000]]])


## 5. Dot Product (Inner Product)

The dot product of two vectors is: `x · y = Σᵢ xᵢ * yᵢ`. In PyTorch, use `torch.matmul()` or `torch.dot()`.

In [6]:
dot_product = torch.matmul(x, y)
print(f"{x} · {y} = {dot_product}")
print(f"Alternative: torch.dot(x, y) = {torch.dot(x, y)}")

tensor([1, 2, 1]) · tensor([1, 2, 2]) = 7
Alternative: torch.dot(x, y) = 7


## 6. Matrix‑Vector and Matrix‑Matrix Multiplication

- **Matrix‑Vector:** `(A x)ᵢ = Σⱼ Aᵢⱼ xⱼ`
- **Matrix‑Matrix:** `(A B)ᵢⱼ = Σₖ Aᵢₖ Bₖⱼ`

Both are performed with `torch.matmul()`.

In [7]:
product = torch.matmul(A, x)
print(f"A = \n{A}")
print(f"x = {x}")
print(f"A · x = {product}")

A = 
tensor([[0, 5, 1],
        [3, 0, 2],
        [0, 2, 0],
        [5, 3, 1]])
x = tensor([1, 2, 1])
A · x = tensor([11,  5,  4, 12])


In [8]:
rank2_product = torch.matmul(A, B.T)
print(f"A · B.T =\n{rank2_product}")

A · B.T =
tensor([[ 2, 21,  5,  0],
        [34, 29, 24,  3],
        [ 0,  8,  2,  0],
        [52, 58, 43,  5]])


## 7. Multiplication with Higher‑Rank Tensors

Tensors of rank 3 or higher can be multiplied with vectors, matrices, or other tensors, provided the dimensions align.

- **Tensor‑Vector:** `(T x)ᵢⱼ = Σₖ Tᵢⱼₖ xₖ`
- **Tensor‑Matrix:** `(T A)ᵢⱼₖ = Σₗ Tᵢⱼₗ Aₗₖ`
- **Tensor‑Tensor:** `(T U)ᵢⱼₖ = Σₗ Tᵢⱼₗ Uₗₖ`

In [9]:
# Create tensors
T3 = torch.rand(3, 3, 3)
A3 = torch.rand(3, 2)
x3 = torch.rand(3)

# Tensor‑Vector
print("Tensor (3x3x3) · Vector (3):")
print(f"T3:\n{T3}")
print(f"x3: {x3}")
print(f"Result:\n{torch.matmul(T3, x3)}")
print("-" * 40)

# Tensor‑Matrix
print("Tensor (3x3x3) · Matrix (3x2):")
print(f"Result:\n{torch.matmul(T3, A3)}")
print("-" * 40)

# Tensor‑Tensor
T4 = torch.rand(3, 3, 3)
print("Tensor (3x3x3) · Tensor (3x3x3):")
print(f"Result:\n{torch.matmul(T3, T4)}")

Tensor (3x3x3) · Vector (3):
T3:
tensor([[[0.0589, 0.9417, 0.9650],
         [0.5351, 0.9280, 0.3340],
         [0.8940, 0.6850, 0.8412]],

        [[0.6975, 0.3642, 0.5164],
         [0.8837, 0.6074, 0.4011],
         [0.8687, 0.5505, 0.9199]],

        [[0.8409, 0.8789, 0.9471],
         [0.5684, 0.4762, 0.8445],
         [0.0784, 0.4789, 0.3216]]])
x3: tensor([0.1476, 0.0022, 0.7960])
Result:
tensor([[0.7790, 0.3469, 0.8031],
        [0.5149, 0.4511, 0.8618],
        [0.8800, 0.7572, 0.2686]])
----------------------------------------
Tensor (3x3x3) · Matrix (3x2):
Result:
tensor([[[1.3144, 1.2844],
         [1.0025, 1.2406],
         [1.0255, 1.7285]],

        [[0.5790, 1.1486],
         [0.7451, 1.3743],
         [0.9411, 1.6778]],

        [[1.2516, 1.8766],
         [0.8366, 1.3337],
         [0.5878, 0.5785]]])
----------------------------------------
Tensor (3x3x3) · Tensor (3x3x3):
Result:
tensor([[[1.3143, 0.4623, 0.9776],
         [1.0304, 0.4443, 1.1745],
         [1.4939,

## 8. Hadamard (Element‑Wise) Product

The Hadamard product multiplies corresponding elements of two tensors of the same shape: `(T ⊙ U)ᵢ = Tᵢ * Uᵢ`. In PyTorch, use the `*` operator.

In [10]:
hadamard = x * y
print(f"{x} ⊙ {y} = {hadamard}")
print(f"Matrix Hadamard product:\n{A * B}")

tensor([1, 2, 1]) ⊙ tensor([1, 2, 2]) = tensor([1, 4, 2])
Matrix Hadamard product:
tensor([[ 0,  0,  2],
        [27,  0,  2],
        [ 0,  2,  0],
        [ 5,  0,  0]])


In [11]:
outer_product = torch.outer(x, y)
print(f"{x} ⊗ {y} = \n{outer_product}")

tensor([1, 2, 1]) ⊗ tensor([1, 2, 2]) = 
tensor([[1, 2, 2],
        [2, 4, 4],
        [1, 2, 2]])


## Summary and Next Steps

**Accomplished:**
- Explored transposition and permutation of tensors.
- Performed addition and scalar multiplication.
- Computed dot products, matrix‑vector, matrix‑matrix, and higher‑rank multiplications.
- Used Hadamard (element‑wise) products.
- Computed outer products.

**Key Insights:**
- Tensor operations are the foundation of all neural network computations.
- PyTorch provides efficient, GPU‑accelerated implementations of these operations.
- Understanding matrix multiplication shapes is crucial for building neural networks.
- Element‑wise operations (`*`) differ from matrix multiplication (`@` / `torch.matmul()`).
- Higher‑rank tensor operations generalise matrix operations and are used in attention mechanisms and convolutional layers.

**Suggested Next Steps:**
1. **Practice with different shapes** – experiment with tensor operations on various dimensions.
2. **Understand broadcasting** – learn how PyTorch handles operations between tensors of different shapes.
3. **Build a computational graph** – use these operations to create a simple neural network.

**Reflection:**
This notebook provides a comprehensive overview of essential tensor operations. Mastering these operations is key to implementing neural networks from scratch and understanding how deep learning frameworks work under the hood.